services:
  web:
    build: ./web
    ports:
      - "8001:8000"

    command: >
      sh -c "uvicorn config.asgi:application --reload --host 0.0.0.0 --port 8000 & python manage.py tailwind watch"

    volumes:
      - ./web:/code
    depends_on:
      - db
    env_file:
      - ./.env.dev
    tty: true

  gotenberg:
    image: gotenberg/gotenberg:8

  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
