# Generated by Django 5.1.1 on 2024-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_available_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('individual', 'Individual'), ('team', 'Team')], default='free', max_length=50),
        ),
    ]
