# Generated by Django 5.1.1 on 2024-10-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='consumed_credits',
        ),
    ]
