# Generated by Django 5.1.1 on 2024-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_consumed_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_credits',
            field=models.IntegerField(default=100),
        ),
    ]
