# Generated by Django 5.1.3 on 2024-11-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_svix_endpoint_id'),
        ('accounts', '0006_alter_customuser_available_credits'),
    ]

    operations = [
    ]
