# Generated by Django 5.1.3 on 2024-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20241121_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='svix_endpoint_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='svix_endpoint_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
