# Generated by Django 5.1.4 on 2024-12-16 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_svix_endpoint_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_pages', models.IntegerField(default=1)),
                ('used_proxy', models.BooleanField(default=False)),
                ('filename', models.CharField(default='N/A', max_length=255)),
                ('request_type', models.CharField(choices=[('upsert', 'Upsert'), ('patch', 'Patch'), ('search', 'Search'), ('filter', 'Filter'), ('embeddings', 'Embeddings')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
